### ISSUE TITLE
Review and update

### ISSUE THREAD

**Issue by b286** [openUC2/UC2_Fluorescence_microscope#1]
Please check that the information provided here is correct and if possible update the repository. Thank you ❤️

**Comment by beniroquai** [comment]
At one point it surely requires an update. But for now it looks great1 Thanks! :)

**Comment by renelachmann** [comment]
Links to CAD-designs seem to be broken, eg

- was: https://github.com/openUC2/UC2-GIT/CAD/ASSEMBLY_Baseplate/
- has to be now: https://github.com/openUC2/UC2-GIT/tree/master/CAD/ASSEMBLY_Baseplate

Maybe this is true for many other repos as well?

**Comment by beniroquai** [comment]
Solved in https://github.com/openUC2/UC2_Fluorescence_microscope/commit/476848b666fb628e6df0b1537673003099818034
